<section id="comentarios" class="">
	<div class="container">
		<div class="row justify-content-center">
		<div class="col-lg-12">

			<div class="fb-comments" style="margin-top: 5px;">
					<div class="fb-comments-header"> <span>28 comentários:</span></div>
					<div class="fb-comments-wrapper" id="1"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/jamylle.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Eva Laura Gonçalves</name> </font> <br> Estou bem feliz. Em 1 semana, já estou tendo resultados só seguindo as dicas iniciais que ele oferece. Eu não sou de fazer isso, mas tinha que vir aqui para agradecer a oportunidade. Muito obrigada!!!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>31</likes> <date>27 min</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="2"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/ana-lucia-oliveira--e1618345548793.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Cristina Albuquerque</name> </font> <br> <name class="mark-comments"><b>Eva Laura Gonçalves</b></name> Sério? Isso funciona mesmo?</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>2</likes> <date>10 min</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="3"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/jamylle.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Eva Laura Gonçalves</name> </font> <br> <name class="mark-comments"><b>Cristina Albuquerque</b></name> Sim, funciona! Eu consegui aumentar minha renda, principalmente fazendo algumas transcrições. Trabalho só 4 horas por dia e já tenho um retorno bem legal... vou me concentrar mais neste trabalho</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>3</likes> <date>1 min</date></td></tr></tbody></table></div>
					<div class="fb-comments-wrapper" id="4">
						<table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/igor.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Martín Feitosa</name> </font> <br> Eu já tinha comprado alguns cursos, mas nenhum diz o que esse método falou. Os outros são só bobagens. Este curso não esconde a verdade e tem um monte de empresas com serviço pra ser feito. Pelo preço, vale muito a pena!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>27</likes> <date>53 min</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="5"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/luciano-1.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Felipe Vasques</name> </font> <br> <name class="mark-comments"><b>Martín Feitosa</b></name> Em quanto tempo você conseguiu resultados?</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>5</likes> <date>42 min</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="6"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/igor.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Martín Feitosa</name> </font> <br> <name class="mark-comments"> <b>Felipe Vasques</b></name> Seguindo exatamente o que foi passado, no primeiro dia eu já consegui o primeiro serviço! Já paguei o investimento do curso e ainda lucrei um pouco!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>7</likes> <date>33 min</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="7"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/luciano-1.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Felipe Vasques</name> </font> <br> <name class="mark-comments"> <b>Martín Feitosa</b></name> Vale a pena então... tinha medo de comprar e que não funcionasse para mim!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>5</likes> <date>27 min</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="8"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/igor.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Martín Feitosa</name> </font> <br> <name class="mark-comments"> <b>Felipe Vasques</b></name> Sim! Honestamente, eu pensei que seria difícil ter resultados, mas é só se dedicar e botar as dicas em prática...</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>3</likes> <date>25 min</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="9"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/luciano-1.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Felipe Vasques</name> </font> <br> <name class="mark-comments"><b>Martín Feitosa</b></name> Valeu mesmo, amigo! Vou comprar aqui também!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <likes>3</likes> <reply>Comentar</reply> · <date>1 min</date></td></tr></tbody></table></div>
					<div class="fb-comments-wrapper" id="10"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/ricardo_vialli.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Alberto Flores </name> </font> <br> Só digo uma coisa... podem se inscrever que vale a pena!!! </td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>63</likes> <date>2 h</date></td></tr></tbody></table></div>
					<div class="fb-comments-wrapper" id="11"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/sueli.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Rosalina Brettas </name> <br> </font> Porque é que tanta gente nos esconde isto? Há um monte de empresas atrás de pessoas para trabalhar, não é possível nem imaginar a dimensão disso!!😉😉😉</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>11</likes> <date>3 h</date></td></tr></tbody></table></div>
					<div class="fb-comments-wrapper" id="24"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/fernandes.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Júlia Fernandes</name> </font> <br> Eu vou comprar!! Pelos comentários, aqui todo mundo está gostando. Em seguida, conto meus resultados aqui!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>62</likes> <date>3 h</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="25"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/nascimento.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Diego Assunção</name> </font> <br> <name class="mark-comments"> <b>Júlia Fernandes</b> </name> Eu gostei muito, eu vou comprar também. Vou te chamar em particular para falar sobre o curso, ok?</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>7</likes> <date>2 h</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="26"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/fernandes.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Júlia Fernandes</name> </font> <br> <name class="mark-comments"> <b>Diego Assunção</b> </name> Eu agradeço, mas meu marido é muito ciumento kkk. Eu sei que seria algo profissional, mas tem a equipe de suporte lá para ajudar...</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>93</likes> <date>1 h</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="27"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/nascimento.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Diego Assunção</name> </font> <br> <name class="mark-comments"> <b>Júlia Fernandes</b> </name> Tranquilo...</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <date>45 min</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-wrapper" id="12"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/augusto_pereira.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Luiz Henrique Pereira </name> </font> <br> Só de ter seguido a dica de fazer transcrição já consegui alguns serviços... feliz demais! Eu pensei que eu não conseguiria porque não sei inglês, mas não é necessário, é muito fácil de seguir... A Internet é uma mãe!!!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>23</likes> <date>3 h</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-wrapper" id="13"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/douglas_lopes.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Rodrigo Ladeira </name> </font> <br> Funciona, pessoal? Alguém pode me dizer?</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>46</likes> <date>4 h</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="14"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/patricia_amorim.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Yonara Santana</name> </font> <br> <name class="mark-comments"> <b>Rodrigo Ladeira</b> </name> Com tantas coisas na Internet, alguém que realmente fez sabe me informar? Não posso entrar em furada.</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes> 6</likes> <date>3 h</date></td></tr></tbody></table></div>
					<div class="fb-comments-reply-wrapper" id="15"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/pessoa-2.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Juan Jose Salvatierra</name> </font> <br> <name class="mark-comments"> <b>Rodrigo Ladeira</b> </name> Olha, eu não acredito em quase nada na internet, mas um amigo me falou muito bem. É só por isso que eu estou pensando em comprar...</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes> 6</likes> <date>3 h</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="16"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/almeida.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Mario Silva</name> </font> <br> <name class="mark-comments"> <b>Rodrigo Ladeira</b> </name> Eu comprei na semana passada e valeu o investimento, irmão! Anteontem consegui um trabalho que será semanal. Só com essa tarefa já paguei esse curso. Boa sorte aí!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>21</likes> <date>3 h</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-reply-wrapper" id="17"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/resende.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Ana Cristina Aguiar</name> </font> <br> <name class="mark-comments"> <b>Mario Silva</b> </name> Eu também, inclusive meu irmão comprou também e agora todos aqui estão fazendo! Eu estou fazendo porque vi meu irmão tendo resultado!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>17</likes> <date>2 h</date></td></tr></tbody></table>
					</div>
					<div class="fb-comments-wrapper" id="18"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/souza.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Luana Rodrigues</name> </font> <br> Olha, gente... O LHO é uma luz no fim do túnel para quem acha que não pode fazer nada. Eles dão toda a base em um passo a passo simples! Me senti obrigada a compartilhar com vocês. Só gratidão e espero que todos consigam também!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>77</likes> <date>6 h</date></td></tr></tbody></table>
					</div>
					 <button class="fb-comments-loadmore" onclick="javascript:loadMore();">Mostrar mais 4 comentários</button><div style="display:none" id="more">
					 	<div class="fb-comments-wrapper" id="19"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/thiago_lira.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Gustavo Cladera</name> </font> <br> Amigos, fiz o pagamento e uma garota que chamou aqui, me pareceu bem profissional. Isso é que eu nem sequer comecei o curso kkkk</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>53</likes> <date>6 h</date></td></tr></tbody></table></div>
					 	<div class="fb-comments-reply-wrapper" id="20"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/diogo_bastos.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Lucas Torres</name> </font> <br> <name class="mark-comments"> <b>Gustavo Cladera</b> </name> Estou no segundo dia e já consegui 3 serviços para 1 semana! Sem palavras!!!!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>13</likes> <date>4 h</date></td></tr></tbody></table></div>
					 	<div class="fb-comments-reply-wrapper" id="21"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/martins.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Nataly Martins</name> </font> <br> <name class="mark-comments"> <b>Gustavo Cladera</b> </name> No primeiro dia, já paguei quase a metade do curso com um serviço que peguei. Feliz!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>32</likes> <date>2 h</date></td></tr></tbody></table></div>
					 	<div class="fb-comments-wrapper" id="22"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/IMG_0067-1.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Ana Gusmão</name> </font> <br> Sem palavras!!!! Agradeço à equipe de suporte!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>53</likes> <date>10 h</date></td></tr></tbody></table></div>
					 	<div class="fb-comments-wrapper" id="23"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/176151093_2841834979407640_3439015475335049722_n.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Graça Miranda</name> </font> <br> Olha... é ótimo poder estar perto da minha família! Ontem mesmo eu estava cansada e tirei uma soneca 2 da tarde !! Depois que acordei, consegui mais dois serviços! 😊😊😊</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>109</likes> <date>12 h</date></td></tr></tbody></table></div>
					 	<div class="fb-comments-wrapper" id="28"><table class="fb-comments-comment"><tbody><tr><td rowspan="3" class="fb-comments-comment-img"><img loading="lazy" src="img/rodrigo_moraes.jpg" width="48" height="48" alt="Imagem de perfil"></td></tr><tr><td class="fb-comments-comment-text"> <font class="fb-comments-comment-name"> <name>Pedro Morais</name> </font> <br> Pessoal, vocês tem que seguir exatamente o passo a passo... falei com a equipe de suporte, e passei a seguir certinho o que foi passado e agora senti que vale a pena. Só gratidão!</td></tr><tr><td class="fb-comments-comment-actions"> <like>Curtir</like> · <reply>Comentar</reply> · <likes>137</likes> <date>21 h</date></td></tr></tbody></table>
					 	</div></div></div>



			<div class="col-12 text-center">
				<small>
					
				</small>
			</div>

			</div>
		</div>
	</div>
</section>
		